version: '3.8'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./epl:/usr/src/app/epl
    ports:
      - "8888:8888"
    command: >
      jupyter notebook --notebook-dir=/usr/src/app/epl
      --ip=0.0.0.0 --port=8888 --no-browser --allow-root
